---
title: "Jackie Tang's CV"
author: Jackie Tang
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
  cache_data:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

<!-- inicio academic icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
<!-- final academic icons -->

<!-- inicio font awesome -->
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
<!-- final font awesome -->



```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1UksSMngO_n0SNxbgIJKlTk2sOtBLrpb5HmXl9GxBQv0/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _tangjackie.github.io_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/tangjackie/CV/blob/master/jackietang_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Skills {#skills}
--------------------------------------------------------------------------------


- <i class="far fa-chart-bar"></i> SAS
- <i class="fas fa-database"></i> SQL
- <i class="fab fa-r-project"></i> R
- <i class="fab fa-python"></i> Python
- <i class="fab fa-html5"></i> HTML
<!-- - <i class="fab fa-markdown"></i> Markdown -->



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

Code available on <i class="fa fa-github"></i> [GitHub](https://github.com/tangjackie/CV).

Last updated on `r Sys.Date()`.



Main
================================================================================

Jackie Tang {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Current Employment Status {data-icon=id-card}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('employment_status')
```


Security Clearance {data-icon=fingerprint}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('security_clearance')
```


Second Language Profile {data-icon=language}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('second_language')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Certificate {data-icon=certificate data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('certificate')
```


Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r}  -->
<!-- CV %<>% print_text_block('work_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('work_experience')
```


Publication {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('publication')
```


<!-- These breaks just force a new page so section doesnt get cut off -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r}  -->
<!-- CV %<>% print_text_block('teaching_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('teaching_positions')
```




